import type { DocumentFileType } from "@legaltech/database";
import type { OcrErrorCode } from "./ocr-provider.js";

/** The representation of a document an OCR execution processes (decision B3 still open). */
export type OcrRepresentation = "ORIGINAL" | "SANITIZED";

/** A `CLEAN` document the worker has claimed for its OCR. */
export interface OcrClaim {
  documentId: string;
  caseId: string;
  fileType: DocumentFileType;
  storageKey: string;
  /** The copy without metadata (JPEG and PNG only). */
  sanitizedStorageKey: string | null;
  fileSize: number;
  /** OCR executions started, this one included. */
  attempts: number;
  /** `ocr_started_at` as PostgreSQL wrote it: the fencing token of the claim. */
  token: string;
}

/** The technical record of a finished execution (decision OCR-A10.6): never any text. */
export interface OcrExecution {
  /** Generated by the worker before the INSERT: it can never read the row back. */
  id: string;
  engine: string;
  engineVersion: string | null;
  representation: OcrRepresentation | null;
  /** SHA-256 of the processed object, never of the text. */
  processedSha256: string | null;
}

export interface CompletedExecution extends OcrExecution {
  representation: OcrRepresentation;
  processedSha256: string;
  pages: number;
}

export interface FailedExecution extends OcrExecution {
  errorCode: OcrErrorCode;
}

/**
 * The OCR columns of the document table as the worker sees them (DATABASE_SPEC.md, "OCR del
 * documento"). Every transition is one conditional statement, and every result is written with its
 * OcrResult row and its audit event in one transaction.
 */
export interface OcrRepository {
  /**
   * PENDING (or a PROCESSING claim older than the lease) → PROCESSING, one more attempt, and only
   * for a `CLEAN` document. Null when there is nothing to do: the job is then a no-op.
   */
  claim(documentId: string, leaseSeconds: number): Promise<OcrClaim | null>;
  /** PROCESSING → COMPLETED + its OcrResult + `document.ocr_completed`. */
  markCompleted(claim: OcrClaim, execution: CompletedExecution): Promise<boolean>;
  /** PROCESSING → FAILED + its OcrResult + `document.ocr_failed`. */
  markFailed(claim: OcrClaim, execution: FailedExecution): Promise<boolean>;
  /**
   * PROCESSING → PENDING with a new `document.ocr` job that starts after `delaySeconds`, in one
   * transaction: a transient error, retried while attempts are left.
   */
  releaseForRetry(claim: OcrClaim, delaySeconds: number): Promise<boolean>;
}
