import { DOCUMENT_OCR_QUEUE, type DocumentOcrJob } from "@legaltech/contracts";
import { Prisma, type PrismaClient } from "@legaltech/database";
import { fromPrisma, type PgBoss } from "pg-boss";
import type {
  CompletedExecution,
  FailedExecution,
  OcrClaim,
  OcrExecution,
  OcrRepository,
} from "./ocr.types.js";

type Tx = Prisma.TransactionClient;

interface ClaimRow {
  id: string;
  case_id: string;
  file_type: OcrClaim["fileType"];
  storage_key: string;
  sanitized_storage_key: string | null;
  file_size: number;
  ocr_attempts: number;
  token: string;
}

/**
 * Prisma-backed OcrRepository, as the worker role (decisions OCR-A10.5 and OCR-A12): SELECT on
 * documents, UPDATE on its OCR state and claim columns only, and INSERT only on ocr_results,
 * ocr_result_pages and audit_logs. Those INSERTs are plain SQL without RETURNING (Prisma's
 * `create()` would read the row back, which the role cannot do): the result's id is generated by
 * the worker before the INSERT, and the pages reference it.
 */
export class PrismaOcrRepository implements OcrRepository {
  constructor(
    private readonly prisma: PrismaClient,
    private readonly boss: PgBoss,
  ) {}

  async claim(documentId: string, leaseSeconds: number): Promise<OcrClaim | null> {
    // One conditional statement: two workers cannot both claim the same document, and nothing but
    // a CLEAN document ever enters the OCR (decision OCR-A6).
    const [row] = await this.prisma.$queryRaw<ClaimRow[]>`
      UPDATE documents
      SET ocr_status = 'PROCESSING',
          ocr_attempts = ocr_attempts + 1,
          ocr_started_at = clock_timestamp()
      WHERE id = ${documentId}::uuid
        AND status = 'CLEAN'
        AND (
          ocr_status = 'PENDING'
          OR (ocr_status = 'PROCESSING'
              AND ocr_started_at < clock_timestamp() - make_interval(secs => ${leaseSeconds}))
        )
      RETURNING id, case_id, file_type, storage_key, sanitized_storage_key, file_size, ocr_attempts,
                ocr_started_at::text AS token`;
    if (!row) return null;
    return {
      documentId: row.id,
      caseId: row.case_id,
      fileType: row.file_type,
      storageKey: row.storage_key,
      sanitizedStorageKey: row.sanitized_storage_key,
      fileSize: row.file_size,
      attempts: row.ocr_attempts,
      token: row.token,
    };
  }

  async markCompleted(
    claim: OcrClaim,
    execution: CompletedExecution,
    pages: readonly string[],
  ): Promise<boolean> {
    if (pages.length !== execution.pages) {
      throw new Error("an OCR execution must record exactly its pages");
    }
    return this.finish(claim, "COMPLETED", execution, {
      pages: execution.pages,
      pageTexts: pages,
      errorCode: null,
      action: "document.ocr_completed",
      // Technical metadata only: never the text (decision OCR-A14).
      newValue: { status: "COMPLETED", pages: execution.pages, attempts: claim.attempts },
    });
  }

  async markFailed(claim: OcrClaim, execution: FailedExecution): Promise<boolean> {
    return this.finish(claim, "FAILED", execution, {
      pages: null,
      pageTexts: [],
      errorCode: execution.errorCode,
      action: "document.ocr_failed",
      newValue: { status: "FAILED", code: execution.errorCode, attempts: claim.attempts },
    });
  }

  async markExcluded(claim: OcrClaim): Promise<boolean> {
    const count = await this.prisma.$executeRaw`
      UPDATE documents SET ocr_status = 'EXCLUDED'
      WHERE id = ${claim.documentId}::uuid
        AND ocr_status = 'PROCESSING'
        AND ocr_started_at = ${claim.token}::timestamptz`;
    return count === 1;
  }

  async releaseForRetry(claim: OcrClaim, delaySeconds: number): Promise<boolean> {
    return this.prisma.$transaction(async (tx: Tx) => {
      const count = await tx.$executeRaw`
        UPDATE documents SET ocr_status = 'PENDING', ocr_started_at = NULL
        WHERE id = ${claim.documentId}::uuid
          AND ocr_status = 'PROCESSING'
          AND ocr_started_at = ${claim.token}::timestamptz`;
      if (count !== 1) return false;
      // The retry is a new job, enqueued with the state change: the worker counts the attempts.
      const job: DocumentOcrJob = { documentId: claim.documentId };
      const jobId = await this.boss.send(DOCUMENT_OCR_QUEUE, job, {
        db: fromPrisma(tx),
        startAfter: delaySeconds,
      });
      if (!jobId) throw new Error("a document.ocr job was not enqueued");
      return true;
    });
  }

  /**
   * Records how an execution ended, its OcrResult, its pages (if any) and its audit event in one
   * transaction, at one PostgreSQL instant, only while the claim is still ours (PROCESSING and the
   * same token). The claim is checked first, so a lost claim writes nothing at all.
   */
  private async finish(
    claim: OcrClaim,
    status: "COMPLETED" | "FAILED",
    execution: OcrExecution,
    detail: {
      pages: number | null;
      /** The text of each page, in order (numbered from 1). Never logged or audited. */
      pageTexts: readonly string[];
      errorCode: string | null;
      action: string;
      newValue: Record<string, unknown>;
    },
  ): Promise<boolean> {
    return this.prisma.$transaction(async (tx: Tx) => {
      const [clock] = await tx.$queryRaw<Array<{ now: Date }>>`SELECT clock_timestamp() AS now`;
      const now = clock!.now;
      const count = await tx.$executeRaw`
        UPDATE documents SET ocr_status = ${status}::document_ocr_status
        WHERE id = ${claim.documentId}::uuid
          AND ocr_status = 'PROCESSING'
          AND ocr_started_at = ${claim.token}::timestamptz`;
      if (count !== 1) return false;
      await tx.$executeRaw`
        INSERT INTO ocr_results (id, document_id, outcome, engine, engine_version, representation,
                                 processed_sha256, pages, attempts, started_at, finished_at,
                                 error_code)
        VALUES (${execution.id}::uuid, ${claim.documentId}::uuid,
                ${status}::ocr_result_outcome, ${execution.engine}, ${execution.engineVersion},
                ${execution.representation}::ocr_representation, ${execution.processedSha256},
                ${detail.pages}, ${claim.attempts}, ${claim.token}::timestamptz, ${now},
                ${detail.errorCode})`;
      if (detail.pageTexts.length > 0) {
        // One statement, parameterized, without RETURNING (OCR-A10.5).
        const rows = detail.pageTexts.map(
          (text, index) => Prisma.sql`(${execution.id}::uuid, ${index + 1}, ${text})`,
        );
        await tx.$executeRaw`
          INSERT INTO ocr_result_pages (ocr_result_id, page_number, text)
          VALUES ${Prisma.join(rows)}`;
      }
      // The system acts: no actor. Never the file name nor any text.
      await tx.$executeRaw`
        INSERT INTO audit_logs (action, entity_type, entity_id, case_id, new_value, occurred_at)
        VALUES (${detail.action}, 'Document', ${claim.documentId}, ${claim.caseId}::uuid,
                ${JSON.stringify(detail.newValue)}::jsonb, ${now})`;
      return true;
    });
  }
}
