-- OCR of a document, first implementation slice (Phase 3; DATABASE_SPEC.md "OCR del documento";
-- decisions OCR-A10 to OCR-A12): the claim columns, the per-execution technical result, the two
-- queues and the worker's privileges. The extracted text itself is NOT stored here: where it lives
-- (PostgreSQL or private object storage) is decision OCR-A10.5, still open. Nothing here gives any
-- runtime role CREATE, and the application role gets nothing on ocr_results yet (no endpoint
-- reads it until the text exists).

-- The claim of the OCR in progress, like the security treatment's (scan_attempts, scan_started_at).
ALTER TABLE "documents"
  ADD COLUMN "ocr_attempts" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "ocr_started_at" TIMESTAMPTZ(6);
ALTER TABLE "documents" ADD CONSTRAINT "documents_ocr_attempts_non_negative" CHECK ("ocr_attempts" >= 0);
CREATE INDEX "documents_ocr_status_idx" ON "documents"("ocr_status");

-- CreateEnum
CREATE TYPE "ocr_result_outcome" AS ENUM ('COMPLETED', 'FAILED');

-- CreateEnum: the representation of the document that was processed (decision B3 still open: the
-- worker's configuration says which one it uses).
CREATE TYPE "ocr_representation" AS ENUM ('ORIGINAL', 'SANITIZED');

-- One row per finished OCR execution (decision OCR-A10.3), immutable: written once by the worker
-- (INSERT only, its id generated by the worker), never updated or deleted. No text, no provider
-- message: a normalized error code only.
CREATE TABLE "ocr_results" (
    "id" UUID NOT NULL,
    "document_id" UUID NOT NULL,
    "outcome" "ocr_result_outcome" NOT NULL,
    "engine" TEXT NOT NULL,
    "engine_version" TEXT,
    "representation" "ocr_representation",
    "processed_sha256" TEXT,
    "pages" INTEGER,
    "attempts" INTEGER NOT NULL,
    "started_at" TIMESTAMPTZ(6),
    "finished_at" TIMESTAMPTZ(6) NOT NULL,
    "error_code" TEXT,

    CONSTRAINT "ocr_results_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "ocr_results" ADD CONSTRAINT "ocr_results_attempts_non_negative" CHECK ("attempts" >= 0);
-- A completed execution says what it processed and how many pages it read, and has no error; a
-- failed one always has its normalized error code.
ALTER TABLE "ocr_results" ADD CONSTRAINT "ocr_results_outcome_consistent" CHECK (
  ("outcome" = 'COMPLETED' AND "error_code" IS NULL AND "pages" IS NOT NULL AND "pages" >= 0
     AND "representation" IS NOT NULL AND "processed_sha256" IS NOT NULL)
  OR ("outcome" = 'FAILED' AND "error_code" IS NOT NULL)
);

-- CreateIndex
CREATE INDEX "ocr_results_document_id_finished_at_idx" ON "ocr_results"("document_id", "finished_at");

-- AddForeignKey
ALTER TABLE "ocr_results" ADD CONSTRAINT "ocr_results_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- The OCR queue, created by the owner like document.scan. Not partitioned: create_queue only
-- inserts a row. The worker counts attempts itself (ocr_attempts) and enqueues the retry of a
-- transient error with its delay, so pg-boss only retries a job that died unexpectedly.
SELECT pgboss.create_queue(
  'document.ocr',
  '{"policy":"standard","retryLimit":2,"retryDelay":30,"retryBackoff":true,"expireInSeconds":900}'::jsonb
);

-- An ADMIN's explicit OCR reprocessing, as document.reprocess: the worker only acts on a document
-- whose OCR is still FAILED, so retrying the job is harmless.
SELECT pgboss.create_queue(
  'document.ocr_reprocess',
  '{"policy":"standard","retryLimit":2,"retryDelay":30,"retryBackoff":true,"expireInSeconds":300}'::jsonb
);

-- The worker (least privilege, decision OCR-A12): it updates only the OCR state and claim columns,
-- and only inserts OCR results. No SELECT on ocr_results: it never reads a result back (no
-- RETURNING; the id is generated before the INSERT). The application role gets nothing here.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'legaltech_worker') THEN
    GRANT UPDATE ("ocr_status", "ocr_attempts", "ocr_started_at") ON TABLE "documents" TO "legaltech_worker";
    GRANT INSERT ON TABLE "ocr_results" TO "legaltech_worker";
  END IF;
END;
$$;
